<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
<!ELEMENT deportistas (deportista+)>
<!ELEMENT deportista (deporte, nombre)>
<!ELEMENT deporte (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
]>

<deportistas>
  <deportista>
    <deporte>Atletismo</deporte>
    <nombre>Jesse Owens</nombre>
  </deportista>
  <deportista>
    <deporte>Natación</deporte>
    <nombre>Mark Spitz</nombre>
  </deportista>
</deportistas>

<!-- Errores solucionados:
  - Rehecha la etiqueta <deporte>. No estaba correctamente anidado.
  - La primera etiqueta <deportista> no estaba cerrada.
-->
