<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas [
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director, autor*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
]>

<peliculas>
  <pelicula>
    <titulo>Con faldas y a lo loco</titulo>
    <director>Billy Wilder</director>
  </pelicula>
  <pelicula>
    <titulo>Sopa de ganso</titulo>
    <director>Leo McCarey</director>
    <autor>barto</autor>
  </pelicula>
</peliculas>

<!-- Errores solucionados:
  - Las etiquetas del segundo elemento estaban al revés.
  - La etiqueta <autor> no estaba bien anidada.
-->
