<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texto [
<!ELEMENT texto (titulo, parrafo+, http)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT parrafo (#PCDATA | abreviatura)*>
<!ELEMENT abreviatura (#PCDATA)>
<!ELEMENT http (#PCDATA)>
]>

<texto>
  <titulo>XML explicado a los niños</titulo>
  <parrafo>El <abreviatura>XML</abreviatura> define cómo crear lenguajes de marcas.</parrafo>
  <parrafo>Las marcas se añaden a un documento de texto para añadir información.</parrafo>
  <http>www.example.org</http>
</texto>

<!-- Errores solucionados:
  - La etiqueta <título> tenía la T mayúscula en la de apertura y minúscula en la de cierre.
  - Eliminadas las tildes de <titulo> y <parrafo>.
-->
